### ISSUE TITLE
CPU and GPU jobs on same node

### ISSUE THREAD

**Issue by MishaZakharchanka** [LLNL/ATS#137]
Codes are packing CPU-only and GPU jobs on the same nodes on sierra-like systems and because of how that creates job launch commands CUDA_VISIBLE_DEVICES isn't correct.

**Comment by MishaZakharchanka** [comment]
Flux was reported doing a good job packing GPU and CPU jobs on one node.

Should we try to use Flux under lsf so that ATS doesn't have to handle this?

**Comment by dawson6** [comment]
Hi @MishaZakharchanka  regarding 'CPU' and "GPU" testing in the same testing run.  I currently advise against this. That is, for a given run, all the jobs should be either CPU testing or they should be GPU testing.

That is, the user should just setup two separate testing runs.

We don't guarantee that mixing CPU only with GPU only will work well using LSF.

**Comment by dawson6** [comment]
But if this is a use case that Flux handles better, then yes, we can pursue using Flux to handle this scenario.

**Comment by dawson6** [comment]
A bit more information.  Mixing CPU and GPU jobs can easily lead to memory issues and running out of memory.  Hence we have not tacked that scenario yet.   I would say that if attempting this with LSF the best option would be to use jsrun and the jsrun exclusive option.  That ensures that each test has a dedicated  set of nodes (whether CPU or GPU), which alleviates much of the memory issues that arise when sharing a node with CPU and GPU jobs.

**Comment by dawson6** [comment]
In discussing 'flux under lsf' on Blueos with Misha, I don't believe this is a priority.  This is based on:

*) There is just one class of BlueOS machines using LSF
*) This machine has an end of life in the next few years
*) Newer platforms will be flux based for the scheduler
*) The current ATS use of LSF works well for scheduling a wide range of jobs, and achieves throughput
*) The flux modules or public flux installations on BlueOS is not necessarily kept up to date it seems 
*) It is best practice at this time to run CPU tests separately fromGPU tests, but this is not really too much of a burden, and can be accomplished with 2 runs of ATS by a project rather than 1
*) Programmer hours would be better spent on meeting an objective of mixing CPU and GPU runs using flux on the next generation machines rather than on Blueos
